### ISSUE TITLE
Excel Dialog hangs when batch call returns errors

### ISSUE THREAD

**Issue by mnavarroruiz** [marianfoo/ui5-cc-excelUpload#208]
Once the batch call is fired, if any error is returned, the dialog will keep on busy state forever:
![Evidence](https://github.com/marianfoo/ui5-cc-excelUpload/assets/119485189/fa919034-2f39-4880-be68-0277ff9fd2f4)
It is possible to reproduce it one live demo (https://excelupload.marianzeis.de/) with the following file:
[Template (1).xlsx](https://github.com/marianfoo/ui5-cc-excelUpload/files/11496709/Template.1.xlsx)

**Comment by marianfoo** [comment]
no luck fixing this error so far
first try with this commit
https://github.com/marianfoo/ui5-cc-excelUpload/pull/213/commits/dc706276a7716a556018e8d8cdc4c6d4e92cb231
Problem is not at V2, only V4

it somehow always crashes at 
```js
await Promise.all(this.odataHandler.createPromises);
```
which is checking the context.created()
https://sapui5.hana.ondemand.com/sdk/#/api/sap.ui.model.odata.v4.Context%23methods/created

only crashes with backend error, no idea how to catch this error because all "try catch" do not work
maybe because of securedExecution?
https://sapui5.hana.ondemand.com/sdk/#/api/sap.fe.core.controllerextensions.EditFlow%23methods/securedExecution

currently out of ideas how to do it :/

**Comment by marianfoo** [comment]
create a Question on the community
https://answers.sap.com/questions/13886695/problem-with-odatav4context-and-created-promise.html

**Comment by wridgeu** [comment]
Hi there,

it looks like this kind of error is not properly (or at all) returned but instead always completely "throws". Responsible for this is the `createInCache`-method (well ... a lot more than that). Here you will also find some of the text that is logged into the console as rejection handler of the internal promise.

This seems to also always abort completely and is not catchable, from what I could tell ... quite deep internally with some syncPromise handling stuff. Which feels odd and makes me question the [create](https://github.com/SAP/openui5/blob/9d59371a68673b0b430602ae97b008647db1c56c/src/sap.ui.core/src/sap/ui/model/odata/v4/ODataListBinding.js#L674-L738) call on the `getBinding` directly ... or well not that itself but rather the try to call the `created` method to figure out if it worked because that in itself doesn't seem too straight forward as mentioned [here](https://github.com/SAP/openui5/blob/9d59371a68673b0b430602ae97b008647db1c56c/src/sap.ui.core/src/sap/ui/model/odata/v4/ODataListBinding.js#L717-L731). 

The [example](https://github.com/marianfoo/ODataV4Created/blob/978c9614fce9d24e7bae59926349561823138b54/webapp/ext/Create.js#L10C5-L17) case doesn't look like a "deepCreate" to me so when I tried getting rid of the `created( )` call and instead used the event `createCompleted` it worked fine for what you're asking for: Being able to know when "created is finished, regardless of succesfull or not". I tried it in the provided example (cool that one is provided!)

Could it be feasable to use the event `attachCreateCompleted`?
> Each time the data for the created entity is sent to the server, a  {@link #event:createSent 'createSent'} event is fired and each time the client receives a response for the creation, a {@link #event:createCompleted 'createCompleted'} event is fired,  independent of whether the creation was successful or not.

Disclaimer: I haven't used OData V4 that much yet and therefore .. question everything! ^^

**Comment by marianfoo** [comment]
Hi Marco,
thank you for your investigation.
You are right that it breaks off completely.
It's just different than expected from how a Promise behaves.
Either it is fullfilled, is pending other rejected.

I also thought about the event, but I have an array of payloads that I create.
For each `create` an event is also thrown.
So I have to somehow match each event with the array and see that everything is completed..
That didn't seem right somehow.

So if i have 5 payloads, something like this.

```js
function waitForEventToBeCalledNTimes(n) {
  return new Promise((resolve, reject) => {
    let counter = 0;

    function onEvent(resolve) {
      counter++;
      if (counter === n) {
        cleanup.call(this, resolve);
      }
    }

    function cleanup(resolve) {
      this.binding.detachCreateCompleted(onEvent);
      resolve();
    }

    this.binding.attachCreateCompleted((oEvent) => onEvent.call(this, resolve));
  });
}

async function main() {
  try {
    await waitForEventToBeCalledNTimes.call(this, 5);
    console.log('Event has been called 5 times');
  } catch (error) {
    console.error('An error occurred:', error);
  }
}

// Call the main function
main.call(this);

```

**Comment by wridgeu** [comment]
Hey Marian,

I see, that makes sense.

I was also caught a bit off-guard seeing that you're unable to do anything with the promise the way a promise **should** work. Technically (at least from the promise perspective) you're obviously not doing anything wrong and even in [UI5 examples](https://github.com/SAP/openui5/blob/df16239514bb13ce7b0f04a7e68eb10c5fb658fb/src/sap.ui.core/test/sap/ui/core/demokit/sample/odata/v4/SalesOrders/Main.controller.js#L143) it is simply handled like a normal promise. Testable [here](https://openui5.hana.ondemand.com/entity/sap.ui.model.odata.v4.ODataModel/sample/sap.ui.core.sample.odata.v4.SalesOrders). 

Odd. 😐

**Comment by marianfoo** [comment]
Created Issue at OpenUI5
https://github.com/SAP/openui5/issues/3760
and question in the SAP Community https://answers.sap.com/questions/13886695/problem-with-odatav4context-and-created-promise.html

**Comment by marianfoo** [comment]
should be fixed with version 0.18.0, waiting for feedback
https://github.com/marianfoo/ui5-cc-excelUpload/blob/main/packages/ui5-cc-excelUpload/CHANGELOG.md#0180-2023-06-02

**Comment by mnavarroruiz** [comment]
Thanks a lot @marianfoo for your work, this is fixed and it works like a charm now! =)

**Comment by marianfoo** [comment]
@mnavarroruiz Happy that i works now.
If you have any more feedback, you´re more then welcome
