### ISSUE TITLE
Deployment with version V0_11_3

### ISSUE THREAD

**Issue by carlostarraf** [marianfoo/ui5-cc-excelUpload#90]
Hello,

I have a problem when deploying to my on-promise environment.

On the first attempt (deploy new) it generates the app normally, but on subsequent attempts it returns this error:

![image](https://user-images.githubusercontent.com/92546147/227633930-28c9a84c-15bd-414e-b407-bff15f3f74ef.png)

I redid all the configurations... even before this version, it was working normally.

If anyone can help me I would be very grateful!

**Comment by marianfoo** [comment]
Thank you for creating the issue.
Do you have a better error log, maybe also from the backend?
Can you please run the ui5 tooling with `--verbose `.
Apparently there is an error but I don't see where exactly.

**Comment by carlostarraf** [comment]
Hi !

of course ! 

[gw_client_data_000D3A1A05B31EEDB2CF4B6402545BE7.txt](https://github.com/marianfoo/ui5-cc-excelUpload/files/11066700/gw_client_data_000D3A1A05B31EEDB2CF4B6402545BE7.txt)

**Comment by marianfoo** [comment]
I can't see 100% which files are causing problems because the complete path is truncated, but it seems to be the typescript files.
![image](https://user-images.githubusercontent.com/13335743/227736895-9d867fef-5fc9-40b0-9cd0-54104b45e422.png)
Do you also have the `exclude` in your deploy yaml file?
https://github.com/marianfoo/ui5-cc-excelUpload/blob/113047d9760293a598bb17c5f79672024932cc06/ui5-deploy.yaml#L25-L26
If i remove this `exclude` i get similar errors:
![image](https://user-images.githubusercontent.com/13335743/227736955-46d7415a-0592-45aa-bfbc-12655420df6f.png)

**Comment by carlostarraf** [comment]
Good afternoon!

Sorry for the delay in answering, I ended up leaving this weekend to spend with the family.

Perfect bro! In my file I didn't have the "EXCLUDE", I put it in and did the tests.. now it's back to working correctly!

Thank you very much for your help and congratulations for the excellent work !!!

An excellent day for you!

**Comment by marianfoo** [comment]
Thanks Carlos, glad it worked
